# Site settings
url: https://lufevida.github.io
baseurl: /html5up-hyperspace
copyright: Untitled
title: Hyperspace
tagline: by HTML5 UP
description: "Just another fine responsive site template designed by <a href="http://html5up.net">HTML5 UP</a><br />and released for free under the <a href="http://html5up.net/license">Creative Commons</a>."
contactTagline: Phasellus convallis elit id ullamcorper pulvinar. Duis aliquam turpis mauris, eu ultricies erat malesuada quis. Aliquam dapibus, lacus eget hendrerit bibendum, urna est aliquam sem, sit amet imperdiet est velit quis lorem.

# Contact
email: name@provider.com