# Site settings
url: https://lufevida.github.io
baseurl: /html5up-hyperspace
title: Hyperspace
tagline: by HTML5 UP
description: "Just another fine responsive site template designed by <a href="http://html5up.net">HTML5 UP</a><br />and released for free under the <a href="http://html5up.net/license">Creative Commons</a>."

# Contact
email: name@provider.com